import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.scss";
import Header from "@/components/Header/Header";
import { StyledEngineProvider, ThemeProvider } from "@mui/material";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { customTheme } from "@/mui/theme";
const inter = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Аспирити",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="ru">
        <body className={inter.className}>
          <AppRouterCacheProvider>
            <StyledEngineProvider injectFirst>
              <ThemeProvider  theme={customTheme}>
                <Header />
                <main>{children}</main>
              </ThemeProvider>
            </StyledEngineProvider>
          </AppRouterCacheProvider>
        </body>
      </html>
  );
}
